### ISSUE TITLE
[BUG][python] Common parameter for a path not working

### ISSUE THREAD

**Issue by nponsard** [openapi-json-schema-tools/openapi-json-schema-generator#237] opened 2023-09-14 12:31 UTC
##### Description

When a [Common path parameter](https://swagger.io/docs/specification/describing-parameters/#common-for-path) is present in a specification, the generator doesn't generate any way to input this parameter in the function (no `path_parameters.py` created in the `paths/users_user_id/get` folder).

Adding the path parameter manually in the method (in the `get:` of the yaml file) the correct files and function get created.

##### openapi-json-schema-generator version

Latest docker image (digest 09665ca30ce8)

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: NetHSM
  version: v1
 servers:
  - url: https://{host}/api/{version}
    variables:
      host:
        default: localhost:8443
      version:
        default: v1
paths:
  /users/{UserID}:
    parameters:
      - name: UserID
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: string
        "401":
          description: Authentication required but none provided.
        "403":
          description: Access denied.
        "404":
          description: User for UserID not found.
        "406":
          description: Content type in Accept header not supported.
        "412":
          description: Precondition failed (NetHSM was not *Operational*).
      description: "Get user info: name and role."
      security:
        - basic: []
      x-annotation-role:
        - Administrator
        - Operator
      x-annotation-state:
        - Operational
      x-test-value-UserID: operator
    put:
      responses:
        "201":
          description: Successful creation of user.
        "400":
          description: Bad request (specified properties are invalid, e.g. weak passphrase).
        "401":
          description: Authentication required but none provided.
        "403":
          description: Access denied.
        "406":
          description: Content type in Accept header not supported.
        "409":
          description: Conflict - user already exists for this user-ID.
        "412":
          description: Precondition failed (NetHSM was not *Operational*).
      description: Create a user on keyfender.
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      security:
        - basic: []
      x-annotation-role:
        - Administrator
      x-annotation-state:
        - Operational
      x-test-value-UserID: newOperator
    delete:
      responses:
        "204":
          description: Successful deletion of user.
        "401":
          description: Authentication required but none provided.
        "403":
          description: Access denied.
        "404":
          description: User not found for this user-ID.
        "406":
          description: Content type in Accept header not supported.
        "412":
          description: Precondition failed (NetHSM was not *Operational*).
      description: Delete a user from keyfender.
      security:
        - basic: []
      x-annotation-role:
        - Administrator
      x-annotation-state:
        - Operational
      x-test-value-UserID: operator
components:
  securitySchemes:
    basic:
      description: |
        NetHSM supports Basic Authentication.
      type: http
      scheme: basic
```

##### Generation Details

executed 
```
docker run --rm -ti -v "${OPENAPI_OUTPUT_DIR}:/out" \
openapijsonschematools/openapi-json-schema-generator-cli:latest generate \
-i=/out/nethsm-api.yaml \
-g=python -o=/out/python --package-name=pynitrokey.nethsm.client
```

##### Steps to reproduce

Run the generator, check the files, no path parameter input in the functions.

**Comment by spacether** [comment] 2023-09-14 18:20
Thank you for posting this. This is a valid corner case that is not yet covered.Are you open to moving this shared parameter into a component? If so, then it will work.

**Comment by nponsard** [comment] 2023-09-14 18:24
Do you mean linking to the path parameter component using $ref in every method of the path ?
I guess this is the most efficient way to make this generator work for us right now.

**Comment by spacether** [comment] 2023-09-14 18:51
Yes, I mean making a component parameter per: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#components-object
And then ref in a parameter definitiin under get/put/delete like so but with a ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/src/test/resources/3_0/python/petstore_customized.yaml#L162

**Comment by spacether** [comment] 2023-10-20 21:27
@nponsard @robin-nitrokey
PathItem parameters have been added in release v3.2.0 which I just published

**Comment by robin-nitrokey** [comment] 2023-10-21 08:29
Thanks!  I tried to use 3.2.0 but it does not work for me:
- On the nethsm-sdk-py codebase, it does not generate path parameters.
- On the example from this issue, it causes a NullPointerException.
- On Example 1, it does not generate the path parameters either.
- On Example 2, I again get a NullPointerException.

Am I missing something?

<details>
<summary>Example 1</summary>

```
openapi: 3.0.0
info:
  title: NetHSM
  version: v1
servers:
  - url: https://{host}/api/{version}
    variables:
      host:
        default: localhost:8443
      version:
        default: v1
paths:
  /users/{UserID}:
    parameters:
      - name: UserID
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: string
      description: "Get user info: name and role."
components:
  securitySchemes:
    basic:
      description: |
        NetHSM supports Basic Authentication.
      type: http
      scheme: basic
```
</details>

<details>
<summary>Example 2</summary>

```
openapi: 3.0.0
info:
  title: NetHSM
  version: v1
servers:
  - url: https://{host}/api/{version}
    variables:
      host:
        default: localhost:8443
      version:
        default: v1
paths:
  /users/{UserID}:
    parameters:
      - name: UserID
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: string
      description: "Get user info: name and role."

```
NPE:
```
Exception in thread "main" java.lang.NullPointerException
        at org.openapijsonschematools.codegen.generatorrunner.DefaultGeneratorRunner.generateRequestBodies(DefaultGeneratorRunner.java:775)
        at org.openapijsonschematools.codegen.generatorrunner.DefaultGeneratorRunner.generate(DefaultGeneratorRunner.java:1456)
        at org.openapijsonschematools.codegen.clicommands.Generate.execute(Generate.java:441)
        at org.openapijsonschematools.codegen.clicommands.AbstractCommand.run(AbstractCommand.java:34)
        at org.openapijsonschematools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:76)
```
</details>

**Comment by spacether** [comment] 2023-10-22 17:57
Hmm it looks like that failure is unrelated. It is caused by `final Map<String, RequestBody> specRequestBodies = this.openAPI.getComponents().getRequestBodies();` throwing a npe because there are no components in your sample. I will post a PR to fix that issue.

**Comment by spacether** [comment] 2023-10-24 03:50
Your remaining issue is a separate one, and I submitted a bug on it here: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/issues/259

**Comment by spacether** [comment] 2023-10-25 20:22
Per investigation path item params are not working in all cases

**Comment by spacether** [comment] 2023-10-25 20:38
Sorry for closing this issue early, working on a fix now which will include more thorough verification.

**Closed** 2023-10-25 21:40 UTC
Labels: bug

**Comment by spacether** [comment] 2023-10-25 22:11
@robin-nitrokey

Can you verify this fix with your code base?
- I added java tests that ensure that parameters are generated in the correct places
- This includes your use case of only one param in an operation that comes from path item params

**Comment by robin-nitrokey** [comment] 2023-10-30 13:38
Thank you for the update!  I can confirm that this fixes the NPE and that code generation now works with our API spec without modification. :)
